### ISSUE TITLE
Providing specific source locations/files yields documentation for nearby files as well

### ISSUE THREAD

**Issue by RonaldTreur** [indieisaconcept/grunt-styleguide#55]
My Grunt config looks like this:
```
project: {
	src: [
		'src/components/**/*.scss',
		'src/main/**/*.scss',
		'src/modules/**/*.scss'
	],
	dest: 'docs/styles/'
}	
```

Grunt will translate this into an array with specific files that adhere to the above globbing patterns. Grunt-styleguide then generates a common basepath (`src/`) and will pass this basePath to Styledocco.

This means I end up with a whole lot more documentation than I need, since I get documentation for all files in `src/`.

Styledocco works just as well, when supplied with a list of specific files. So I'm not sure why this alternate route is being taken to get the documentation. Perhaps KSS works differently? But in that case I would like to propose Styledocco is simply handled the way a user would expect.

**Comment by indieisaconcept** [comment]
@RonaldTreur if you are using kss I recommend you now use https://www.npmjs.com/package/grunt-kss
