### ISSUE TITLE
error: file to import not found or unreadable

### ISSUE THREAD

**Issue by alycda** [indieisaconcept/grunt-styleguide#61]
Hi,

Would you be willing to add an option for import paths (such as for vendor imports) or perhaps a comment flag to ignore specific imports?

**Comment by hupf** [comment]
Hi @indieisaconcept, I think I can give you an example: I'm using SASS with Compass (via ```grunt-contrib-compass```). I have the following statement in my stylesheet to be able to use the Mixins provided by Compass:

```@import 'compass';```

This leads to the following error, as this SCSS file is not in the search path:

```
error: file to import not found or unreadable: 'compass'
```

I think this is what @alycda means with "vendor imports".

**Comment by indieisaconcept** [comment]
@alycda I recommend if you are using KSS to use the following. It will simplify things considerably. 

https://www.npmjs.com/package/grunt-kss
