### ISSUE TITLE
kss/sass error: "error reading values after ..."

### ISSUE THREAD

**Issue by frederickk** [indieisaconcept/grunt-styleguide#62]
I'm trying to compile a folder of .scss files in to a kss styleguide and getting the following error:

```
Error during generation

src/scss/bs-constants.scss:17: error: error reading values after "0"
```

After a fair bit of Googling and combing through various blogs and [forums](http://foundation.zurb.com/forum/posts/19063-grunt---error-error-reading-values-after----libsass). Could it be the sass compiler that grunt-styleguide uses?

As best I can discern the error can be traced back to my usage of [sass maps](https://github.com/sass/sass/blob/master/doc-src/SASS_CHANGELOG.md#sassscript-maps)

Here's a snippet of the sass map that seems to be hanging up the system.

```
$layers: (
    "0" : -200,
    "1" :    0,
    "2" :  200,
    "3" :  400,
    "4" :  600,
    "5" :  800,
    "6" : 1000
);
```

Additionally here's a snippet of my gruntfile.js

```
        styleguide: {
                options: {
                    template: {
                        src: './styleguide/template/'
                    },
                    framework: {
                        name: 'kss'
                    }
                },
                all: {
                    files: [{
                        './documentation/': './src/scss/lib.scss'
                    }]
                }
        }
```

Any help would be much appreciated.

Ken

**Comment by indieisaconcept** [comment]
@frederickk node-kss has removed all pre-compilation of Sass in future versions from 2.0. It's my intention to upgrade styleguide to use this new version which will mean you will have to use a separate grunt task for the sass compilation. Then in the options you would just specify the generated CSS to include.

**Comment by frederickk** [comment]
That sounds great, as I'm already compiling my SASS with a separate task already. Looking forward to the next release.

**Comment by indieisaconcept** [comment]
@frederickk if you are using kss exclusively I recommend you use https://www.npmjs.com/package/grunt-kss
