### ISSUE TITLE
declaration RegExp pattern is missing

### ISSUE THREAD

**Issue by Mishurin** [indieisaconcept/grunt-styleguide#64]
Seems like it should be replaced in kss.js (kss template) by rulePattern or something else.
ruleMatches = rule.cssText.match(declaration);

**Comment by Mishurin** [comment]
https://github.com/kneath/kss/blob/master/example/public/javascripts/kss.js

**Comment by indieisaconcept** [comment]
@Mishurin if you are using kss i recommend you migrate to using grunt-kss.

**Comment by Mishurin** [comment]
Thank you! I will take a look
